version: '3.7'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elastic
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
      - ELASTICSEARCH_SSL_CERTIFICATE=/certs/elastic-certificates.pem
      - ELASTICSEARCH_SSL_KEY=/certs/elastic-certificates.pem
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./certs:/certs
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.10
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=https://elastic:9200
    ports:
      - 5601:5601
    # Elasticsearch Start Dependency
    depends_on:
      - es
    volumes:
      - ./certs:/certs
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge

volumes:
  esdata:
    driver: local
